### ISSUE TITLE
iter_parse method

### ISSUE THREAD

**Issue by jquast** [jquast/blessed#29]
Acceptance Criteria
--------------------------

A method, ``term.iter_parse()``, that can be used in the following manner:
```
>>> for part in Terminal().iter_parse('\x1b[10Cblahblah\x1b[0m'):
...    print((ucs, ucs.is_sequence, ucs.capname, ucs.params))
...
('\x1b[10C', True, 'cuf', ('10',))
('blahblah', False, None, None))
('\x1b[0m', True, 'sgr', ('0',))
```

There are several places in the codebase where sequences are "iterated", these sections of code should be replaced by the new ``iter_parse(term, ucs)`` function added to blessings/sequences.py, and proxying stub method added to the Terminal class.

Details
----------

One thing blessed does right now is simply emit or strip sequences, but it doesn't "comprehend" them in the way curtsies might be able to. 

The value yielded should be a namedtuple() instance, values ``.ucs(str), .is_sequence(bool), .capname(str), .params(tuple(str))``

This can be achieved by modifying the regex parse builders in blessed/sequences.py to include ``(?P<name>...)`` in the expressions compiled.

**Comment by jquast** [comment]
An alogorithm is duplicated in at lease 3 places of blessed that would use this method,

```
            nxt = 0
            for idx in range(0, len(chunk)):
                if idx == nxt:
                    # at sequence, point beyond it,
                    nxt = idx + measure_length(chunk[idx:], term)
                if nxt <= idx:
                    # point beyond next sequence, if any,
                    # otherwise point to next character
                    nxt = idx + measure_length(chunk[idx:], term) + 1
                if Sequence(chunk[:nxt], term).length() > space_left:
                    break
```

**Comment by thomasballinger** [comment]
I'm looking at this now and looking at using helpers like

    def make_term_re(capname):
        return u'?P<{}>{}'.format(capname, re.escape(getattr(term, capname)))

to annotate the patterns in sections of code like

    return set(filter(None, [
        # print_screen: Print contents of screen
        re.escape(term.mc0),
        # prtr_off: Turn off printer
        re.escape(term.mc4),
        # prtr_on: Turn on printer
        re.escape(term.mc5),

**Comment by jquast** [comment]
absolutely, that is the underlying intention.

**Comment by thomasballinger** [comment]
2 issues so far:
* regexes capture group names have to be unique (so have to incorporate nparams and basenum in _build_[any_]numeric_capability into capture group name, this is fine)
* in Python <3.5, only 100 named groups are allowed: https://bugs.python.org/issue22437

It looks like both of these are fixed in https://pypi.python.org/pypi/regex, but I imagine the dependency isn't worth it. (?)

I imagine it's a big speed hit and a bit of a code complexity hit to write Python code to try the regexes in succession instead of the pipe-joined large ones, but that's the first thing that comes to mind. Maybe just splitting up the regex groups more - `_re_wont_move` only has 53 elements (with whatever terminal environment I'm testing), but unfortunately unnamed capture groups within a named capture group seem to count against this max. I'll think about this some more, interested to hear any thoughts.

**Comment by jquast** [comment]
thanks for your research time,

On regex
------------

- A primary project goal is C-code independence, so the dependency **is not worth it**.

On 100 named limit
--------------------------

Right, I see the problems, here.

Two thoughts,

- Teamcity CI system tracks the duration of each test ... so simply give it a push and see how bad it really is before boiling over complex code. the tests around textwrap are especially abusive on regex pattern matching.

- consider building a primary set of patterns matching only the ``capname``. Now, with this unique identifier, we can consult a hash of secondary patterns, if discovered, keyed by capname, we re-match the same pattern to additionally provide named parameters.

**Comment by thomasballinger** [comment]
Thanks, I'll give this a shot tomorrow.
