### ISSUE TITLE
[Question] A raw_input-like returning when <Enter> OR <Escape> key pressed? 

### ISSUE THREAD

**Issue by Kraymer** [jquast/blessed#49]
I well see how to react to an individual <kbd>ESC</kbd> key press.
But I'd be interested to have a function that return (or raise) when <kbd>ESC</kbd> key is pressed and keep ``raw_input``behaviour otherwise.

Is that easy with blessed or does that mean reimplementing all ``raw-input`` internals?

**Comment by jquast** [comment]
You could derive and override getch() to act immediately on \x1b or \x0d https://github.com/jquast/blessed/blob/master/blessed/terminal.py#L548

You ask, "keep ``raw_input`` behaviour otherwise." But I am not clear which behaviour. For example, the arrow keys begin with escape, you wish to continue decoding arrow keys? Escape is particularly tricky, as one needs to incrementally decode multibyte sequences.

Irregardless, anything you should wish to do, should be possible by deriving and re-writing the inkey() method to suite your needs. https://github.com/jquast/blessed/blob/master/blessed/terminal.py#L670

**Comment by Kraymer** [comment]
Merci.

**Comment by jquast** [comment]
Pas de problème.
