### ISSUE TITLE
Location() context manager doesn't seem to work on Mac OSX Terminal

### ISSUE THREAD

**Issue by oilnam** [jquast/blessed#50]
I'm not sure wether this is a bug or I'm missing something, but `location()` context manager doesn't work on the OS X Terminal. E.g.:

```python
term = Terminal()
with term.location(0, term.height - 1):
    print('Here is the bottom.')
print('This is back where I came from.')
```
the cursor position doesn't go back to its previous position upon exit, so that *this is back where I came from* is actually printed *after* the line *here is the bottom*.

Great library anyway, thanks!

**Comment by jquast** [comment]
Cannot reproduce.

I have OSX. I am using Bash. My TERM is xterm-256color. I am using iTerm2. I am using the version of blessed available on pypi at the time of your report, 1.9.5. Fails to reproduce, https://asciinema.org/a/d5jaomafsc0ti5qwxpzb7vbh0

**Comment by oilnam** [comment]
I confirm that with iTerm2 that code works just fine; when I said "Mac OSX Terminal" I meant the default terminal app that comes with OSX, called Terminal.

**Comment by jquast** [comment]
Terminal.app uses the same 'xterm-256color' TERM kind, so there is no reason it would have been any different, but to entertain you, it also does not reproduce on Terminal.app. https://asciinema.org/a/1b221p7s4fn2yyv8gb9k0rmyh

There are 43 tests related to ``location()`` context manager verified and tested on an OSX build slave for every commit. https://teamcity-master.pexpect.org/viewLog.html?buildId=15360&buildTypeId=Blessed_MacOs&tab=testsInfo

Please create a pull request that suggests how any of tests can be augmented or duplicated to show the failure you are seeing, I don't think your failure is a legitimate bug, otherwise.
